version: "3"
# https://stackoverflow.com/questions/58765127/permanently-install-vs-codes-server-in-container
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
      - vscode-server:/home/code/.vscode-server

volumes:
  vscode-server: