#!/bin/bash

####### MAILA Interface  #######
alias MAILA_source="source ${MAILA_ROOT_DIR}/scripts/environment.sh"
alias MAILA_cd="cd ${MAILA_ROOT_DIR}"
alias MAILA_cds="cd ${MAILA_ROOT_DIR}/src"
alias MAILA_cdd="cd ${MAILA_ROOT_DIR}/devel"
alias MAILA_cdi="cd ${MAILA_ROOT_DIR}/install"        


# Build maila project
alias MAILA_force_clean="MAILA_cd && rm -rf build/ install/ log/"
MAILA_build() {
  # https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/
  MAILA_cd
  if [ $# == 0 ]; then
    colcon build --symlink-install --event-handlers console_direct+
  else
    colcon build --symlink-install --event-handlers console_direct+ --packages-up-to $1
  fi
}


# PRINT
# Maila init message
MAILA_init_console() {
  clear
  printf "\n"
  printf "Maila workspace \n"
  printf "Version 0.1 - 2020"
  printf "\n\n"
}

# Maila init message
MAILA_logo() {
  printf "\n\n"
  printf "+============================================+\n"
  printf "|                                            |\n"
  printf "|               o       o                    |\n"
  printf "|                \_____/                     |\n"
  printf "|                /=O=O=\     _______         |\n"
  printf "|               /   ^   \   /\\\\\\\\\\\\\\\\   \        |\n"
  printf "|               \ \___/ /  /\   ___  \       |\n"
  printf "|                \_ V _/  /\   /\\\\\\\\ \  \      |\n" 
  printf "|                  \  \__/\   /\ @_/  /      |\n"
  printf "|          ________ \____\____\______/ __    |\n"
  printf "|                                            |\n"
  printf "+============================================+\n"
  MAILA_init_console
  printf "\n\n"
}
####### END MAILA Interface  #######

####### DOCKER Interface  #######

# Connect current terminal to a running docker container
d_bash (){
  docker exec -it maila-container bash
}

# Run the maila docker container
d_run () {
  if [ $# == 0 ]; then
    docker run --rm -it \
       --name maila-container -h maila \
       --user "$(id -u):$(id -g)" \
       --mount type=bind,src="$PWD"/../,dst=/mailamaca \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       --env DISPLAY=$DISPLAY \
       -p 2222:22 \
       ${MAILA_DOCKER_IMAGE}
  else
     export IMAGE_NAME=maila/maila-dev
     docker run --rm -it \
         --name maila-container -h maila \
         --user "$(id -u):$(id -g)" \
         --mount type=bind,src="$PWD"/../,dst=/mailamaca \
         -v /tmp/.X11-unix:/tmp/.X11-unix \
         --env DISPLAY=$DISPLAY \
         -p 2222:22 \
         ${MAILA_DOCKER_IMAGE} \
         $1
  fi

}

####### END DOCKER ALIASES  #######
